### ISSUE TITLE
An Error Occured issues in Firefox browser for Bard extension.

### ISSUE THREAD

**Issue by Tod-911** [Dj0ulo/OptiSearch#15]
Whenever I try to search for anything, I get an ⚠️ An error occurred. I live in India, I have access to google Bard, I had been using it for a month now. But all of a sudden it shows error occurred. 
For context: I am using Firefox browser, with the extension provided from the add-on manager.
![Error](https://github.com/Dj0ulo/OptiSearch/assets/74495889/d976ea47-2c56-452a-aad3-02f11acd0d02)

**Comment by Dj0ulo** [comment]
Hi,
Thanks a lot for reporting this issue. The Bard API has indeed changed. It should be fixed now with the version 1.0.3
Let me know if it still doesn't work with the new version.

**Comment by Tod-911** [comment]
Hi, 
It works great now, thanks for fixing the issue asap.
