### ISSUE TITLE
The error code 061+8=0x22

### ISSUE THREAD

**Issue by Awesome126** [Dj0ulo/OptiSearch#19]
It all works well until yesterday. Every moment I look for a query in Google Search and look forwards to responses from the extension as it works usually, an error code 061+8=0x22 appears, and after it the extension refused to give info out but just the same code every time. I can access Bing, Bing Chat, and chat with it joyfully through its official entrance. Minor possibility to be a connection error, either, for the situation persists until the other morning. Btw, I am using Google Chrome in which the Bing Chat is just allowed to be used since yesterday (before that I am using another extension to bypass the access in Chrome). I wonder what could that be, 061+8=0x22

**Comment by Eikosa** [comment]
I'm having this problem too

**Comment by boromyr** [comment]
Me too

**Comment by Darskiy** [comment]
Me too

**Comment by Darskiy** [comment]
The same problem

**Comment by Dj0ulo** [comment]
Hello !
Thank you for reporting the issue !
Bing is now controlling the origin header of a request. This means that if we prompt it from a website other than bing.com it will throw this weird error message (which I am still wondering the meaning).

Anyway I am currently working on a workaround but it involves launching a external tab to make the request from it. It should be deployed next week.

**Comment by Dj0ulo** [comment]
It should be fixed now, at least on chromium browser. Let me know if it's not working on your side
