### ISSUE TITLE
Logged in but extension asking for Bing Login consistently

### ISSUE THREAD

**Issue by Awesome126** [Dj0ulo/OptiSearch#22]
I've logged in the Bing, and can access Bing as well as Bing Chat directly through its pages. But the extension just won't access it and keep asking me to log in to Bing (Log out and log in again won't works, too). Recent issue appearing just today. Would like your quick fix, thanks.

**Comment by Dj0ulo** [comment]
On which browser are you?

**Comment by Awesome126** [comment]
> On which browser are you?

Google Chrome 117.0.5938.63, Windows 10

**Comment by Awesome126** [comment]
![image](https://github.com/Dj0ulo/OptiSearch/assets/124046981/4e11ba1c-869b-438c-a081-775250615ce5)

this is the situation. although click in and it will go through Bing website and log in automatically since I've already logged in before this, the icon still persists and refuse to show any response instead of that 😓

**Comment by Karnbir** [comment]
+1 Same issue using latest MS Edge on MacOS Sonoma

**Comment by Dj0ulo** [comment]
Okay I have finally been able to reproduce and fix the issue, it should be deployed this week. I'll let you know when it is ;)

**Comment by yiugn** [comment]
same issue here

**Comment by Dj0ulo** [comment]
It just got deployed! Maybe restart your browser and check on the extension popup that you have version 2.0.1 and let me know if it is fixed
![image](https://github.com/Dj0ulo/OptiSearch/assets/46035353/3ea1411a-89aa-4a15-8a25-6cb923dba294)

**Comment by Karnbir** [comment]
Fixed for me!

**Comment by Awesome126** [comment]
Fixed. Thank you.
