### ISSUE TITLE
 Please login to ChatGPT, then refresh.

### ISSUE THREAD

**Issue by bigplayer-ai** [Dj0ulo/OptiSearch#3]
chatgpt and bard is not loading properly.
 Please login to ChatGPT, then refresh :
![Clip_20230603_102709](https://github.com/Dj0ulo/OptiSearch/assets/119108387/cb05d6d8-deb6-4cc1-b93d-7898243c42e9)

**Comment by Dj0ulo** [comment]
Thanks for reporting the issue with Bard. For ChatGPT however, this means that you have been disconnected from their site. If you login again, it should work

**Comment by bigplayer-ai** [comment]
I think I found the problem, It interfere with other privacy extensions. I can close this Issue.
Sorry for any inconvenience.
