### ISSUE TITLE
Bard Multiple Account Access Bug

### ISSUE THREAD

**Issue by Eikosa** [Dj0ulo/OptiSearch#34]
![image](https://github.com/Dj0ulo/OptiSearch/assets/20538090/594263a9-b56e-481b-bbcb-d7b9b049fb89)
I have more than one account on my account, and it gives me this error even though I am 100% sure that they both have access. Active it button also does nothing

**Comment by sherman-yang** [comment]
yes, for me it gets another Google account and no way to change the account.
