### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by shahin365** [Dj0ulo/OptiSearch#37]
Whenever I search for something, I receive the message "_Waiting for ChatGPT…_" but nothing happens. I have even uninstalled and reinstalled the extension from the Chrome Web Store but the issue persists.

![0Iw6eFd](https://github.com/Dj0ulo/OptiSearch/assets/16749755/5aac58e9-f02a-44e1-b936-0a9abd1d6055)

**Comment by Dj0ulo** [comment]
Hi thanks for the feedback! Could you send me what's in the chrome console. There might be an error appearing there

**Comment by zhangfangzhou01** [comment]
Hi developer, I also encountered the same problem, no error is reported in the console in my browser, and a new conversation is created on the chatgpt side, but the extension is always stuck at "waiting for chatgpt".

**Comment by zhangfangzhou01** [comment]
<img width="485" alt="屏幕截图 2024-03-04 223706" src="https://github.com/Dj0ulo/OptiSearch/assets/76115617/7da9adb8-712b-4a8c-9f26-8e63f6ba6cc7">
<img width="503" alt="屏幕截图 2024-03-04 223723" src="https://github.com/Dj0ulo/OptiSearch/assets/76115617/d1d92bbd-ef70-4117-80bd-c7622400babd">

**Comment by shahin365** [comment]
> Hi thanks for the feedback! Could you send me what's in the chrome console. There might be an error appearing there

hi thanks for the response. somehow I missed it. the problem persists. both Chrome & Firefox. I think @zhangfangzhou01 screenshot would help? Are you considering fixing it?

**Comment by Dj0ulo** [comment]
Hi I would like to fix this issue but I am not able to reproduce it on my side. Also there is no error related to OptiSearch in the screenshots. What might help me is that you send the HAR file of the background requests:
- Click on the little extensions icon
![image](https://github.com/Dj0ulo/OptiSearch/assets/46035353/98ee4465-1066-4bc2-b37b-832087f722e8)
- Then, "Manage Extensions"
- There, make sure Developer mode is activated (top right of the page)
![image](https://github.com/Dj0ulo/OptiSearch/assets/46035353/10e0111f-2046-49c6-b500-5995053f5663)
- Inspect view from the service worker of OptiSearch
![image](https://github.com/Dj0ulo/OptiSearch/assets/46035353/2dd1d598-2089-4cf4-8b51-037018abe244)
- Go to the "Network" tab
- Now do a search in bing (or whatever search engine) and ask ChatGPT using OptiSearch
- Finally, go back to the service worker network tab, export HAR file by clicking here
![image](https://github.com/Dj0ulo/OptiSearch/assets/46035353/f75cd903-55ce-4ba7-8f05-08d6d3a0422c) and send it here

Thanks for your cooperation!

**Comment by zhangfangzhou01** [comment]
> Hi I would like to fix this issue but I am not able to reproduce it on my side. Also there is no error related to OptiSearch in the screenshots. What might help me is that you send the HAR file of the background requests:
> 
> * Click on the little extensions icon
>   ![image](https://private-user-images.githubusercontent.com/46035353/313485179-98ee4465-1066-4bc2-b37b-832087f722e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjA3NjAsIm5iZiI6MTcxMDgyMDQ2MCwicGF0aCI6Ii80NjAzNTM1My8zMTM0ODUxNzktOThlZTQ0NjUtMTA2Ni00YmMyLWIzN2ItODMyMDg3ZjcyMmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAzNTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NGVlNjk3M2U4OTM1ZGY2MDcxYTljZTM2MTc5N2U1MjgxOTAyYWZjYzcyN2Q2ZGJkOTI2Nzk0NDhkNmZhN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tgs8ZN0hoC0qraIaFzx5z2-nJggUmEgGcFw-MYGp7_w)
> * Then, "Manage Extensions"
> * There, make sure Developer mode is activated (top right of the page)
>   ![image](https://private-user-images.githubusercontent.com/46035353/313485325-10e0111f-2046-49c6-b500-5995053f5663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjA3NjAsIm5iZiI6MTcxMDgyMDQ2MCwicGF0aCI6Ii80NjAzNTM1My8zMTM0ODUzMjUtMTBlMDExMWYtMjA0Ni00OWM2LWI1MDAtNTk5NTA1M2Y1NjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAzNTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MmE2NjM0NmNjMWM2MzA1Yzg4YTE0YzljOGQ4ZmYwN2E1NDIyY2VhMmNiZTMxMzM5Yzc1ZmNhYmIwMzZlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.74klohbmOCerKU2Nh0tABIx9G5itlhTOZQSHvtRU4oc)
> * Inspect view from the service worker of OptiSearch
>   ![image](https://private-user-images.githubusercontent.com/46035353/313485359-2dd1d598-2089-4cf4-8b51-037018abe244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjA3NjAsIm5iZiI6MTcxMDgyMDQ2MCwicGF0aCI6Ii80NjAzNTM1My8zMTM0ODUzNTktMmRkMWQ1OTgtMjA4OS00Y2Y0LThiNTEtMDM3MDE4YWJlMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAzNTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YjhlOTk2NTY3YmM4YWM3MDVkMDFkNTJhYjkwNGFjOTg1MjEyOGNmN2YxNjY2NzgxNmFlYTdiOGQ3YjRhYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mNx7gQbxzJ8CaqCw6lVazc1_nQ18lrJorhjX0zeauOU)
> * Go to the "Network" tab
> * Now do a search in bing (or whatever search engine) and ask ChatGPT using OptiSearch
> * Finally, go back to the service worker network tab, export HAR file by clicking here
>   ![image](https://private-user-images.githubusercontent.com/46035353/313485848-f75cd903-55ce-4ba7-8f05-08d6d3a0422c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjA3NjAsIm5iZiI6MTcxMDgyMDQ2MCwicGF0aCI6Ii80NjAzNTM1My8zMTM0ODU4NDgtZjc1Y2Q5MDMtNTVjZS00YmE3LThmMDUtMDhkNmQzYTA0MjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAzNTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYjk1N2Y2N2U2M2VmMWJmYWExY2RiYzA2Y2VjZDA5YjA2MTY2NjQ4NzdlMTMwMzcxZjc4NGQ4NzUxZmMxNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HnbDg7S9ipacWhobpMUhbqqqgn9qhRayVdsEDh_ui84) and send it here
> 
> Thanks for your cooperation!

[Uploading network-log.zip…]()

**Comment by zhangfangzhou01** [comment]
[network-log.zip](https://github.com/Dj0ulo/OptiSearch/files/14645071/network-log.zip)

**Comment by Dj0ulo** [comment]
Thanks a lot @zhangfangzhou01! I will investigate this. (I removed your comment because I realized that the HAR file might contain sensible information about your sessions, I should have asked you to send me this in private)

**Comment by Dj0ulo** [comment]
@shahin365 @zhangfangzhou01 I made an update, could you try again and tell me if it is working now? Make sure you have the version 3.7.1 of OptiSearch

**Comment by zhangfangzhou01** [comment]
I tried, still the same...
btw the response of the conversation is status 400
{
    "detail": "There was a problem with your chat request. Please use a different browser or try again later."
}
<img width="1082" alt="image" src="https://github.com/Dj0ulo/OptiSearch/assets/76115617/ab2a1839-bd9f-4299-9e19-c2a0cdd21eb6">

**Comment by shahin365** [comment]
> @shahin365 @zhangfangzhou01 I made an update, could you try again and tell me if it is working now? Make sure you have the version 3.7.1 of OptiSearch

I reinstalled it from the Chrome Store today, and it works after today's update! Thank you. (Haven't checked Firefox yet).

**Comment by Dj0ulo** [comment]
Thanks for the feedback! The issue finally appeared yesterday on my side. I guess OpenAI doesn't make their API updates for everyone at the same time.
Anyway at least I could fix it. :tada:
