### ISSUE TITLE
Extension keeps asking me to log-in to my ChatGPT account even though I'm already logged-in

### ISSUE THREAD

**Issue by shahin365** [Dj0ulo/OptiSearch#48]
**Extension keeps asking me to log-in to my ChatGPT account even though I'm already logged-in.**

Broken again. keep asking to log in (I'm already logged in). It keeps asking me to log in even though I'm already logged in. I tried removing and reinstalling the extension, but the issue persists. Please fix it.

**Comment by IliasWhoElse** [comment]
Have the same issue

**Comment by shahin365** [comment]
> Have the same issue. I've installed the extension on Edge

Seems the developer seems to have given up on all three of these extensions. The Gemini extension used to show images, but now it only displays text in brackets instead. Recently, this extension was updated, and since then, it has completely stopped working. 

![Screenshot 2024-07-02 at 8 47 40 AM](https://github.com/Dj0ulo/OptiSearch/assets/16749755/821c5ea1-fd79-4299-9bb7-662678c329fe)
![Screenshot 2024-07-02 at 8 57 16 AM](https://github.com/Dj0ulo/OptiSearch/assets/16749755/6ea21743-1afc-4e8f-a3cb-33375dada8ce)

**Comment by Dj0ulo** [comment]
Hi thanks for the feedback. I did not gave up on updating those extensions. But since they rely on external services that keep changing all the time and not in the same way for every user, I am sometimes just not aware of the new bugs that appear..

I recently made a bug fix for ChatGPT because they decided to add some complex computations that was not trivial to reverse engineer. But it now works on my side. I will see what I can do for this new error.

Regarding the image problem with Gemini, I'll look into it. It seems that Google (again) changed something. But note that you are actually the first to mention it to me.

**Comment by shahin365** [comment]
> Hi thanks for the feedback. I did not gave up on updating those extensions. But since they rely on external services that keep changing all the time and not in the same way for every user, I am sometimes just not aware of the new bugs that appear..
> 
> I recently made a bug fix for ChatGPT because they decided to add some complex computations that was not trivial to reverse engineer. But it now works on my side. I will see what I can do for this new error.
> 
> Regarding the image problem with Gemini, I'll look into it. It seems that Google (again) changed something. But note that you are actually the first to mention it to me.

Thank you for your prompt response. I was somewhat disappointed earlier as I had reported Optisearch bugs here, in the Chrome extension store, and in the Firefox add-ons store, but did not receive a response. It's good to hear from you now. I appreciate your attention and I am looking forward to seeing the bugs fixed in future updates. Thank you for the great tools and your continued support.

### **Update:**

The Gemini extension on Chrome has been fixed after today's update 👍 Assume the FF update is yet to come.

Regarding Optisearch, I'm getting 2 different errors in Chrome and FF.

chrome: 
`⚠️ TypeError: Cannot read properties of undefined (reading '0')`

FF: 
`⚠️ TypeError: data.message.content.parts is undefined`

![Screenshot 2024-07-03 at 10 09 39 AM](https://github.com/Dj0ulo/OptiSearch/assets/16749755/e30fbbcb-34f6-43b5-8e1f-39f4b6ea7855)

![Screenshot 2024-07-03 at 10 09 26 AM](https://github.com/Dj0ulo/OptiSearch/assets/16749755/0e56a119-375b-4815-8c0c-54c094c72f3b)

**Comment by Dj0ulo** [comment]
Great! At least we are moving somewhere. It's a bit complicated to fix this issue since I do not get it on my side but your input is very valuable. I'll look into it :smile:

**Comment by shahin365** [comment]
> Great! At least we are moving somewhere. It's a bit complicated to fix this issue since I do not get it on my side but your input is very valuable. I'll look into it 😄

Today's update fixed it on Chrome (no update on FF yet). It's working after a long time!
again, Thank you for the great tools and your continued support.

**Comment by IliasWhoElse** [comment]
Thank you!
