### ISSUE TITLE
undefined bard

### ISSUE THREAD

**Issue by bigplayer-ai** [Dj0ulo/OptiSearch#5]
chatgpt and bard is not loading properly.
Please login to ChatGPT, then refresh :
![Clip_20230603_102904](https://github.com/Dj0ulo/OptiSearch/assets/119108387/0d1409fb-04b7-4a62-948f-fb255c364351)

**Comment by Dj0ulo** [comment]
Do you have this all the time ?
Are you connected with a Google account with your browser ?
In which country are you located (because Bard is not available in all country yet)?

**Comment by bigplayer-ai** [comment]
I think I found the problem, It interfere with other privacy extensions. I can close this Issue.
Sorry for any inconvenience.
