### ISSUE TITLE
can you add by OptiSearch for all the results of your extensions?

### ISSUE THREAD

**Issue by bigplayer-ai** [Dj0ulo/OptiSearch#6]
Hey,
can you add by OptiSearch for all the results of your extensions?
IDK if this is yours or google's when searching I want to know which one is for who?

**Comment by bigplayer-ai** [comment]
this is related to #2 somehow.

**Comment by Dj0ulo** [comment]
They all have "OptiSearch" written in the top right corner if they come from OptiSearch extension. That's not the case for the BingChat/Bard extension however but it's pretty straightforward to differentiate them, isn't it 🤨

**Comment by bigplayer-ai** [comment]
Even I think it is better to have your watermark on them. Consistency is a key.
