### ISSUE TITLE
Allowed sites only for sites your extension needs to use. This make your extension more privacy friendly.

### ISSUE THREAD

**Issue by bigplayer-ai** [Dj0ulo/OptiSearch#7]
Allowed sites only for sites your extension needs to use. This make your extension more privacy friendly.

**Comment by Dj0ulo** [comment]
That's what I do, could you give an example please.

**Comment by bigplayer-ai** [comment]
I meant Site access for the given extension (extension manager)
![Clip_20230604_010144](https://github.com/Dj0ulo/OptiSearch/assets/119108387/b63a338a-cbe0-4d28-a0ba-04156ae91957)

**Comment by Dj0ulo** [comment]
Well I don't control that. This is an option for you to control which specific sites you want my extension to access. If you select "On all sites" it will just access the sites from which you gave your authorization at the installation.

**Comment by bigplayer-ai** [comment]
NVM, this is a really extra feature for privacy's sake, no need (closing the issue).
